# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-19 06:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=100)),
                ('bint_mobile', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_sale', models.DateField()),
                ('dbl_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbl_service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('int_paid_status', models.IntegerField()),
                ('int_staus', models.IntegerField()),
                ('vchr_ref_no', models.CharField(max_length=10)),
                ('dat_created', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 19, 6, 59, 36, 937280))),
                ('fk_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cust_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='salesdata',
            name='fk_service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cust_app.Services'),
        ),
    ]
