# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-19 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cust_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='salesdata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'managed': False},
        ),
    ]
